# Generated by Django 4.0.1 on 2022-01-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='saldo_cardano',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='carteira',
            name='saldo_libra',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='apostaformula1',
            name='moeda',
            field=models.CharField(choices=[('E', 'Euro'), ('$', 'Dolar'), ('D', 'Dogecoin'), ('B', 'Bitcoin'), ('C', 'Cardano'), ('L', 'Libra')], default='Euro', max_length=100),
        ),
        migrations.AlterField(
            model_name='apostafutebol',
            name='moeda',
            field=models.CharField(choices=[('E', 'Euro'), ('$', 'Dolar'), ('D', 'Dogecoin'), ('B', 'Bitcoin'), ('C', 'Cardano'), ('L', 'Libra')], default='Euro', max_length=100),
        ),
    ]
