# Generated by Django 4.0.1 on 2022-01-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0002_carteira_saldo_cardano_carteira_saldo_libra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apostaformula1',
            name='lucro',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='apostafutebol',
            name='lucro',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=16),
        ),
    ]
